# TLD
# Must contains the first "."
tld:
    - '.netlib.re'
    - '.autre.tld'

tmpdir: /tmp

database:
    sgbd: mysql # other options : see DBI module
    name: dnsmanager
    host: localhost
    port: 3306
    user: monutilisateur
    passwd: motdepasse

primarydnsserver:
    app: bind9
    dnsslavekey: key-slave.netlib.re
    zonedir: ssh://dnsmanager@host:2222/var/named/rndczones/
    domain:
        name: my.example.com
        v4: 192.0.2.1       # optional
        v6: 2001:db8::1     # optional

secondarydnsserver:
    - app: nsd3
      cfg: ssh://dnsmanager@host2:2222/etc/nsd3/nsd.conf
      domain:
          name: second.example.com
          v4: 192.0.2.2       # optional
          v6: 2001:db8::2     # optional

    - app: nsd3
      cfg: ssh://dnsmanager@host3:2222/etc/nsd3/nsd.conf
      domain:
          name: third.example.com
          v4: 192.0.2.3       # optional
          v6: 2001:db8::3     # optional
