# TLD
# Must contains the first "."
tld:
    - '.netlib.re'
    - '.autre.tld'

tmpdir: file:///media/fast/

database:
    sgbd: mysql # other options : see DBI module
    name: dnsmanager
    host: localhost
    port: 3306
    user: dnsmanageruser
    passwd: "my-not-so-dummy-password"

primarydnsserver:
    app: bind9
    dnsslavekey: demokey
    zonedir: ssh://root@localhost:22/var/named/zones/rndczones/
    domain:
        user: root
        port: 22
        host: localhost
        name: localhost
        v4: 127.0.0.1       # optional
        v6: ::1             # optional

secondarydnsserver:
    - app: nsd
      cfg: ssh://root@nsdl:22/etc/nsd/nsd.conf
      zonedir: ssh://root@nsdl:22/etc/nsd/
      domain:
          name: nsdl
          v4: 192.168.0.61          # optional
          v6: 2001:db8::2           # optional

#    - app: nsd
#      cfg: ssh://dnsmanager@host3:2222/etc/nsd3/nsd.conf
#      domain:
#          name: third.example.com
#          v4: 192.0.2.3       # optional
#          v6: 2001:db8::3     # optional
